'use client'

export default function Tutorial () {
    return (
        <main className="page-main">

            {/* INTRO */}
            <section className={`intro-section page-content-section`}>
                <p className={`scia-paragraph intro`}>
                    This page lists the main procedures. These include installation, recovery, and update procedures. They are necessary in order to use the control unit.
                </p>

                <div className="blockquote scia-blockquote-warning">
                    <p className="blockquote-paragraph">
                        During flashing or updates, do not disconnect the power supply or USB.  
                        If something goes wrong, the recovery procedure (reinstalling the boot with erase) will restore the situation.
                    </p>
                </div>
            </section>


            {/* OVERVIEW */}
            <section id="overview" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Overview</h1>
                <section id="overview-1" className={`page-content-subsection subsection-box`}>
                    <h2 className={`scia-leadText scia-margin-b-8 scia-typo-medium`}>1) Bootloader (ESP32)</h2>
                    <p className={`scia-paragraph`}>
                        This is a standard component of the ESP32 (second-stage bootloader) generated by the build.  
                        Its task is to launch the correct app by reading the partition table.
                    </p>
                </section>
                <section id="overview-2" className={`page-content-subsection subsection-box`}>
                    <h2 className={`scia-leadText scia-margin-b-8 scia-typo-medium`}>2) BOOT (App0/Boot UI)</h2>
                    <p className={`scia-paragraph`}>This is a service app that:</p>
                    <ul className={`page-content-list page-content-ulist`}>
                        <li>creates a Wi-Fi access point</li>
                        <li>allows you to configure the network</li>
                        <li>allows you to install/update Luna via OTA</li>
                    </ul>
                </section>
                <section id="overview-3" className={`page-content-subsection subsection-box`}>
                    <h2 className={`scia-leadText scia-margin-b-8 scia-typo-medium`}>3) Firmware (Luna / Main app)</h2>
                    <p className={`scia-paragraph`}>
                        This is the “real” application of the control unit. At this stage, it is installed by BOOT via Wi-Fi (OTA).
                    </p>
                </section>
                <section id="overview-4" className={`page-content-subsection subsection-box`}>
                    <h2 className={`scia-leadText scia-margin-b-8 scia-typo-medium`}>4) Partitions and data</h2>
                    <p className={`scia-paragraph`}>
                        The flash memory is divided into different areas (NVS, OTA data, BOOT, Luna, storage).  
                        There is no need to manage them manually: the ZIP package and BOOT take care of everything.
                    </p>
                </section>
            </section>


            {/* REQUIREMENTS */}
            <section id="requirements" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Requirements</h1>
                <section id="requirements-hardware" className={`page-content-subsection subsection-box`}>
                    <h2 className={`scia-leadText scia-margin-b-8 scia-typo-medium`}>Hardware</h2>
                    <ul className={`page-content-list page-content-ulist`}>
                        <li>Alina Vista control unit (ESP32) + USB data cable</li>
                        <li>Know the size of your flash memory (4 MB / 8 MB / 16 MB) to download the correct package.</li>
                    </ul>
                </section>
                <section id="requirements-software" className={`page-content-subsection subsection-box`}>
                    <h2 className={`scia-leadText scia-margin-b-8 scia-typo-medium`}>Software</h2>
                    <ul className={`page-content-list page-content-ulist`}>
                        <li>macOS/Linux: Terminal</li>
                        <li>Windows: Command Prompt or PowerShell</li>
                        <li>Python 3</li>
                        <li>esptool</li>
                    </ul>
                </section>
            </section>


            {/* METHOD A */}
            <section id="method-A" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Method A: Minimal installation (recommended)</h1>
                <p className={`scia-paragraph`}>
                    Install only BOOT via USB (with ZIP package). Then configure Wi-Fi from BOOT and install Luna via OTA.
                </p>
                <section id="method-A-step-A1" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Step A1 — Download the correct BOOT package</h3>
                    <ol className={`page-content-list`}>
                        <li>Go to the <strong>Downloads</strong> page</li>
                        <li>Download the <strong>BOOT</strong> ZIP file for your flash size (4MB/8MB/16MB)</li>
                        <li>Extract the ZIP file to a folder (Desktop or Documents)</li>
                    </ol>
                </section>
                <section id="method-A-step-A2" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Step A2 — Enter programming mode (EN/BOOT)</h3>
                    <p className={`scia-paragraph`}>See the dedicated section: <a href="programming-mode">Programming mode (EN/BOOT)</a>.</p>
                </section>
                <section id="method-A-step-A3" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Step A3 — Run the installation script (with erase)</h3>
                    <p className={`scia-paragraph`}>This procedure erases the flash and reinstalls: bootloader, partition table, and BOOT UI.</p>

                    <h4 className={`scia-h4 scia-margin-t-12`}>macOS / Linux</h4>
                    <pre className={`scia-code-block`}>
                        <code>
{`cd /path/to/extracted-folder
chmod +x install_mac_linux.sh
./install_mac_linux.sh <PORT>`}
                        </code>
                    </pre>
                    Typical port examples:
                    <ul className={`page-content-list page-content-ulist`}>
                        <li>macOS: /dev/tty.usbserial-XXXX or /dev/tty.SLAB_USBtoUART</li>
                        <li>Linux: /dev/ttyUSB0</li>
                    </ul>

                    <h4 className={`scia-h4 scia-margin-t-12`}>Windows</h4>
                    <pre className={`scia-code-block`}>
                        <code>
{`cd \percorso\della\cartella-estratta
install_windows.bat COM5`}
                        </code>
                    </pre>
                </section>
                <section id="method-A-step-A4" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Step A4 — Restart and access BOOT (App0)</h3>
                    <ol className={`page-content-list`}>
                        <li>Restart the board (or disconnect/reconnect USB)</li>
                        <li>If Luna is not installed, the control unit automatically enters BOOT (App0)</li>
                        <li>Connect to the Wi-Fi AP created by BOOT (SSID shown in the BOOT UI)</li>
                        <li>Open the BOOT web page (IP indicated in the BOOT UI)</li>
                    </ol>
                </section>
                <section id="method-A-step-A5" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Step A5 — Configure Wi-Fi and install Luna via OTA</h3>
                    <ol className={`page-content-list`}>
                        <li>From the BOOT page, configure the Wi-Fi network (SSID + password)</li>
                        <li>Wait for connection</li>
                        <li>From the “Firmware” section of BOOT, select Luna and start OTA</li>
                        <li>BOOT downloads, verifies, and writes the firmware to the correct partition, then restarts</li>
                    </ol>

                    <div className="blockquote scia-blockquote-info">
                        <p className="blockquote-paragraph">
                            <b>Why this is the recommended mode?</b> The user does not need to know offsets or partitions. BOOT manages provisioning and OTA in a controlled manner.
                        </p>
                    </div>
                </section>
            </section>


            {/* METHOD B */}
            <section id="method-B" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Method B: Manual installation</h1>
                <p className={`scia-paragraph`}>
                    It is possible to use esptool “manually,” but it is easy to make mistakes with the offset and create inconsistencies. 
                    The ZIP package exists precisely to avoid these errors. Therefore, we recommend using method A. 
                    This alternative is recommended only for experienced users for testing, debugging, and software modifications.
                    Alternatively, it is also possible to use an IDE (such as Platformio) to flash firmware (boot and app) via USB.
                </p>
            </section>


            {/* METHOD C */}
            <section id="method-C" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Method C: Future updates</h1>
                <p className={`scia-paragraph`}>
                    This method can only be used to update the control unit. It is assumed that the first installation has already been carried out.
                </p>
                <section id="method-C-update-luna" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Update Luna (app firmware)</h3>
                    <ul className={`page-content-list`}>
                        <li>Main flow: from BOOT via OTA</li>
                        <li>BOOT downloads and installs Luna in the correct partition</li>
                    </ul>
                </section>
                <section id="method-C-update-boot" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Update BOOT (boot firmware)</h3>
                    <p className={`scia-paragraph`}>
                        Only updates the Boot UI without deleting data or firmware.
                    </p>

                    <h4 className={`scia-h4 scia-margin-t-12`}>macOS / Linux</h4>
                    <pre className={`scia-code-block`}>
                        <code>
{`./update_boot_mac_linux.sh <PORTA>`}
                        </code>
                    </pre>

                    <h4 className={`scia-h4 scia-margin-t-12`}>Windows</h4>
                    <pre className={`scia-code-block`}>
                        <code>
{`update_boot_windows.bat COM5`}
                        </code>
                    </pre>
                    
                    <div className="blockquote scia-blockquote-info">
                        <p className="blockquote-paragraph">
                            <b>When NOT to use boot-only update?</b> If you have doubts or if the device is in a “strange” state, use the complete reinstallation (install with erase).
                            The boot-only update is an advanced procedure.
                        </p>
                    </div>
                </section>
            </section>


            {/* ENTERING BOOT MODE */}
            <section id="entering-boot-mode" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Entering BOOT mode</h1>
                <section id="entering-boot-auto" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Automatic start-up</h3>
                    <p className={`scia-paragraph`}>If Luna is not present or is invalid, the control unit automatically enters BOOT.</p>
                </section>
                <section id="entering-boot-luna" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Entering BOOT when Luna is already installed</h3>
                    <p className={`scia-paragraph`}>
                        If Luna is installed, it will normally start up. To enter BOOT, you must use the procedure provided by the user interface.
                        From the Luna menu: select “Restart in BOOT mode”.
                    </p>
                </section>
            </section>


            {/* PROGRAMMING MODE (EN/BOOT) */}
            <section id="programming-mode" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Programming mode (EN/BOOT)</h1>
                <p className={`scia-paragraph`}>
                    To write the flash via USB (esptool/script), the ESP32 must enter programming mode (boot ROM mode).
                </p>
                <section id="standard-procedure" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Standard procedure</h3>
                    <ol className={`page-content-list`}>
                        <li>Hold down BOOT</li>
                        <li>Press and release EN (reset)</li>
                        <li>Release BOOT after 1–2 seconds</li>
                    </ol>
                    <div className="blockquote scia-blockquote-info">
                        <p className="blockquote-paragraph">
                            If it doesn't work the first time: calmly repeat the sequence and check that the USB port is correct.
                        </p>
                    </div>
                </section>
            </section>


            {/* INSTALLING & USING ESPTOOL */}
            <section id="esptool" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Installing and using esptool</h1>
                <section id="esptool-install" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Installation</h3>
                    <p className="scia-paragraph">Ensure you have Python 3, then:</p>
                    <pre className={`scia-code-block`}>
                        <code>{`pip install esptool`}</code>
                    </pre>
                </section>
                <section id="esptool-find-port" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Finding the serial port</h3>

                    <h4 className={`scia-h4 scia-margin-t-12`}>macOS</h4>
                    <pre className={`scia-code-block`}>
                        <code>{`ls /dev/tty.*`}</code>
                    </pre>
                    <p className="scia-paragraph">Tipical: <code className="scia-code">/dev/tty.usbserial-XXXX</code> o <code className="scia-code">/dev/tty.SLAB_USBtoUART</code></p>

                    <h4 className={`scia-h4 scia-margin-t-12`}>Linux</h4>
                    <pre className={`scia-code-block`}>
                        <code>{`ls /dev/ttyUSB* /dev/ttyACM*`}</code>
                    </pre>
                    <p className="scia-paragraph">Tipical: <code className="scia-code">/dev/ttyUSB0</code></p>
                    
                    <h4 className={`scia-h4 scia-margin-t-12`}>Windows</h4>
                    <p className="scia-paragraph">Open “Device Manager” → “Ports (COM and LPT)” and read the port (e.g., <code className="scia-code">COM5</code>).</p>
                    <p className="scia-leadText scia-typo-semibold">Quick test</p>
                    <pre className={`scia-code-block`}>
                        <code>{`esptool.py --port <PORT> chip_id`}</code>
                    </pre>
                </section>
            </section>


            {/* BOOT ZIP PACKAGE */}
            <section id="zip-package" className={`page-content-section`}>
                <h1 className={`scia-h2`}>BOOT ZIP package</h1>
                <p className="scia-paragraph">
                    The BOOT ZIP package is a “one-shot” package: download, extract, run a script.
                    It includes everything you need to start the control unit in BOOT mode.
                </p>
                <section id="zip-package-content" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Typical contents</h3>
                    <ul className={`page-content-list`}>
                        <li>
                            <code className="scia-code">bin/</code>
                            <ul className={`page-content-list`}>
                                <li><code className="scia-code">bootloader.bin</code></li>
                                <li><code className="scia-code">partitions.bin</code></li>
                                <li><code className="scia-code">alina-boot-ui.bin</code></li>
                            </ul>
                        </li>
                        <li><code className="scia-code">install_mac_linux.sh</code></li>
                        <li><code className="scia-code">update_boot_mac_linux.sh</code></li>
                        <li><code className="scia-code">install_windows.bat</code></li>
                        <li><code className="scia-code">update_boot_windows.bat</code></li>
                        <li><code className="scia-code">README.md</code></li>
                    </ul>
                </section>
                <section id="zip-package-choice" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Which ZIP should you choose?</h3>
                    <ul className={`page-content-list`}>
                        <li>Choose the ZIP that corresponds to your flash size (4MB / 8MB / 16MB).</li>
                        <li>If you do not know the flash size, refer to the documentation for your model/hardware.</li>
                    </ul>
                </section>
            </section>


            {/* PARTITIONS */}
            <section id="partitions" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Partitions</h1>
                <p className="scia-paragraph">
                    The flash memory is divided into areas. The partition table (flashed as partitions.bin) describes this map.
                    You do not need to modify it manually to install: the ZIP and BOOT handle everything.
                </p>
                <section id="partitions-typical" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>Typical partitions</h3>
                    <ul className={`page-content-list`}>
                        <li><strong>NVS</strong>: persistent settings (Wi-Fi, configurations)</li>
                        <li><strong>OTA data</strong>: metadata to know which firmware is active</li>
                        <li><strong>Boot</strong>: the Boot UI (provisioning + OTA)</li>
                        <li><strong>Luna</strong>: main (app) firmware</li>
                        <li><strong>Storage</strong>: filesystem (SPIFFS) for advanced resources/logs/config</li>
                    </ul>
                </section>
                <section id="partitions-should-know" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>What should you know?</h3>
                    <ul className={`page-content-list`}>
                        <li>A full erase also resets NVS (you will lose configurations)</li>
                        <li>The “update boot-only” procedure does not delete data: useful, but more delicate</li>
                    </ul>
                </section>
            </section>


            {/* COMMON PROBLEMS */}
            <section id="common-problems" className={`page-content-section`}>
                <h1 className={`scia-h2`}>Common problems</h1>
                <section id="common-problems-1" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>1) The script cannot find the port / connection error</h3>
                    <ul className={`page-content-list`}>
                        <li>Check the programming mode (EN/BOOT)</li>
                        <li>Check the port (mac: <code className="scia-code">ls /dev/tty.*</code>, linux: <code className="scia-code">/dev/ttyUSB*</code>, <code className="scia-code">windows: COM</code>)</li>
                        <li>Try: <code className="scia-code">{`esptool.py --port <PORT> chip_id`}</code></li>
                    </ul>
                </section>
                <section id="common-problems-2" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>2) After flashing, BOOT is not working</h3>
                    <ul className={`page-content-list`}>
                        <li>Make sure you used the install script (with erase) at least the first time</li>
                        <li>Check that you downloaded the ZIP file with the correct flash size</li>
                        <li>Repeat the complete reinstallation (recovery)</li>
                    </ul>
                </section>
                <section id="common-problems-3" className={`page-content-subsection`}>
                    <h3 className={`scia-h3`}>3) Luna is installed but you want to enter BOOT mode</h3>
                    <ul className={`page-content-list`}>
                        <li>Use the menu item/procedure provided by Luna</li>
                        <li>If you can't: recovery via USB</li>
                    </ul>
                </section>
            </section>
        </main>
    );
}
